name: Run the S3 Lister

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'Specific bucket name to list (optional)'
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # For OIDC authentication

    steps:
      - run: echo "Skip"