name: Tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - run: echo "Skip"